### ISSUE TITLE
AttributeError: 'function' object has no attribute 'setter'

### ISSUE THREAD

**Issue by pchwalek** [Tanganelli/CoAPthon3#43]
Getting the following issue when running the latest commit

`Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from coapthon.server.coap import CoAP
  File "/home/pi/dev/captivate_server/dataViz/CoAPthon3/coapthon/server/coap.py", line 9, in <module>
    from coapthon.layers.blocklayer import BlockLayer
  File "/home/pi/dev/captivate_server/dataViz/CoAPthon3/coapthon/layers/blocklayer.py", line 5, in <module>
    from coapthon.messages.request import Request
  File "/home/pi/dev/captivate_server/dataViz/CoAPthon3/coapthon/messages/request.py", line 2, in <module>
    from coapthon.messages.message import Message
  File "/home/pi/dev/captivate_server/dataViz/CoAPthon3/coapthon/messages/message.py", line 12, in <module>
    class Message(object):
  File "/home/pi/dev/captivate_server/dataViz/CoAPthon3/coapthon/messages/message.py", line 656, in Message
    @size1.setter
AttributeError: 'function' object has no attribute 'setter'
`

**Comment by pchwalek** [comment]
This issue is solved by the following request: https://github.com/Tanganelli/CoAPthon3/pull/39/commits/9be6559133ba7ba07f23fdaa3ffccf37b3fc8f36
